package DAO;
// Generated 18 fvr. 2019 11:30:37 by Hibernate Tools 4.3.1



/**
 * AvoirResultatId generated by hbm2java
 */
public class AvoirResultatId  implements java.io.Serializable {


     private int idcli;
     private int idscprog;
     private int idprog;
     private int idtypeex;

    public AvoirResultatId() {
    }

    public AvoirResultatId(int idcli, int idscprog, int idprog, int idtypeex) {
       this.idcli = idcli;
       this.idscprog = idscprog;
       this.idprog = idprog;
       this.idtypeex = idtypeex;
    }
   
    public int getIdcli() {
        return this.idcli;
    }
    
    public void setIdcli(int idcli) {
        this.idcli = idcli;
    }
    public int getIdscprog() {
        return this.idscprog;
    }
    
    public void setIdscprog(int idscprog) {
        this.idscprog = idscprog;
    }
    public int getIdprog() {
        return this.idprog;
    }
    
    public void setIdprog(int idprog) {
        this.idprog = idprog;
    }
    public int getIdtypeex() {
        return this.idtypeex;
    }
    
    public void setIdtypeex(int idtypeex) {
        this.idtypeex = idtypeex;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AvoirResultatId) ) return false;
		 AvoirResultatId castOther = ( AvoirResultatId ) other; 
         
		 return (this.getIdcli()==castOther.getIdcli())
 && (this.getIdscprog()==castOther.getIdscprog())
 && (this.getIdprog()==castOther.getIdprog())
 && (this.getIdtypeex()==castOther.getIdtypeex());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcli();
         result = 37 * result + this.getIdscprog();
         result = 37 * result + this.getIdprog();
         result = 37 * result + this.getIdtypeex();
         return result;
   }   


}


