package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idcli;
     private Statutclient statutclient;
     private Typeabonnement typeabonnement;
     private Typeclient typeclient;
     private String nomcli;
     private String prenomcli;
     private Date datenaisscli;
     private String mailcli;
     private String telcli;
     private String pjcli;
     private Set evaluerexcercices = new HashSet(0);
     private Set programmes = new HashSet(0);
     private Set avoirResultats = new HashSet(0);
     private Set seancebilans = new HashSet(0);

    public Client() {
    }

	
    public Client(Statutclient statutclient, Typeabonnement typeabonnement, Typeclient typeclient) {
        this.statutclient = statutclient;
        this.typeabonnement = typeabonnement;
        this.typeclient = typeclient;
    }
    public Client(Statutclient statutclient, Typeabonnement typeabonnement, Typeclient typeclient, String nomcli, String prenomcli, Date datenaisscli, String mailcli, String telcli, String pjcli, Set evaluerexcercices, Set programmes, Set avoirResultats, Set seancebilans) {
       this.statutclient = statutclient;
       this.typeabonnement = typeabonnement;
       this.typeclient = typeclient;
       this.nomcli = nomcli;
       this.prenomcli = prenomcli;
       this.datenaisscli = datenaisscli;
       this.mailcli = mailcli;
       this.telcli = telcli;
       this.pjcli = pjcli;
       this.evaluerexcercices = evaluerexcercices;
       this.programmes = programmes;
       this.avoirResultats = avoirResultats;
       this.seancebilans = seancebilans;
    }
   
    public Integer getIdcli() {
        return this.idcli;
    }
    
    public void setIdcli(Integer idcli) {
        this.idcli = idcli;
    }
    public Statutclient getStatutclient() {
        return this.statutclient;
    }
    
    public void setStatutclient(Statutclient statutclient) {
        this.statutclient = statutclient;
    }
    public Typeabonnement getTypeabonnement() {
        return this.typeabonnement;
    }
    
    public void setTypeabonnement(Typeabonnement typeabonnement) {
        this.typeabonnement = typeabonnement;
    }
    public Typeclient getTypeclient() {
        return this.typeclient;
    }
    
    public void setTypeclient(Typeclient typeclient) {
        this.typeclient = typeclient;
    }
    public String getNomcli() {
        return this.nomcli;
    }
    
    public void setNomcli(String nomcli) {
        this.nomcli = nomcli;
    }
    public String getPrenomcli() {
        return this.prenomcli;
    }
    
    public void setPrenomcli(String prenomcli) {
        this.prenomcli = prenomcli;
    }
    public Date getDatenaisscli() {
        return this.datenaisscli;
    }
    
    public void setDatenaisscli(Date datenaisscli) {
        this.datenaisscli = datenaisscli;
    }
    public String getMailcli() {
        return this.mailcli;
    }
    
    public void setMailcli(String mailcli) {
        this.mailcli = mailcli;
    }
    public String getTelcli() {
        return this.telcli;
    }
    
    public void setTelcli(String telcli) {
        this.telcli = telcli;
    }
    public String getPjcli() {
        return this.pjcli;
    }
    
    public void setPjcli(String pjcli) {
        this.pjcli = pjcli;
    }
    public Set getEvaluerexcercices() {
        return this.evaluerexcercices;
    }
    
    public void setEvaluerexcercices(Set evaluerexcercices) {
        this.evaluerexcercices = evaluerexcercices;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }
    public Set getAvoirResultats() {
        return this.avoirResultats;
    }
    
    public void setAvoirResultats(Set avoirResultats) {
        this.avoirResultats = avoirResultats;
    }
    public Set getSeancebilans() {
        return this.seancebilans;
    }
    
    public void setSeancebilans(Set seancebilans) {
        this.seancebilans = seancebilans;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + Objects.hashCode(this.idcli);
        hash = 83 * hash + Objects.hashCode(this.nomcli);
        hash = 83 * hash + Objects.hashCode(this.prenomcli);
        hash = 83 * hash + Objects.hashCode(this.datenaisscli);
        hash = 83 * hash + Objects.hashCode(this.mailcli);
        hash = 83 * hash + Objects.hashCode(this.telcli);
        hash = 83 * hash + Objects.hashCode(this.pjcli);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Client other = (Client) obj;
        if (!Objects.equals(this.nomcli, other.nomcli)) {
            return false;
        }
        if (!Objects.equals(this.prenomcli, other.prenomcli)) {
            return false;
        }
        if (!Objects.equals(this.mailcli, other.mailcli)) {
            return false;
        }
        if (!Objects.equals(this.telcli, other.telcli)) {
            return false;
        }
        if (!Objects.equals(this.pjcli, other.pjcli)) {
            return false;
        }
        if (!Objects.equals(this.idcli, other.idcli)) {
            return false;
        }
        if (!Objects.equals(this.datenaisscli, other.datenaisscli)) {
            return false;
        }
        return true;
    }




}


