package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private Integer idcoach;
     private String mailadmin;
     private String mailcoach;
     private String nomcoach;
     private String prenomcoach;

    public Coach() {
    }

    public Coach(String mailadmin, String mailcoach, String nomcoach, String prenomcoach) {
       this.mailadmin = mailadmin;
       this.mailcoach = mailcoach;
       this.nomcoach = nomcoach;
       this.prenomcoach = prenomcoach;
    }
   
    public Integer getIdcoach() {
        return this.idcoach;
    }
    
    public void setIdcoach(Integer idcoach) {
        this.idcoach = idcoach;
    }
    public String getMailadmin() {
        return this.mailadmin;
    }
    
    public void setMailadmin(String mailadmin) {
        this.mailadmin = mailadmin;
    }
    public String getMailcoach() {
        return this.mailcoach;
    }
    
    public void setMailcoach(String mailcoach) {
        this.mailcoach = mailcoach;
    }
    public String getNomcoach() {
        return this.nomcoach;
    }
    
    public void setNomcoach(String nomcoach) {
        this.nomcoach = nomcoach;
    }
    public String getPrenomcoach() {
        return this.prenomcoach;
    }
    
    public void setPrenomcoach(String prenomcoach) {
        this.prenomcoach = prenomcoach;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.idcoach);
        hash = 59 * hash + Objects.hashCode(this.mailadmin);
        hash = 59 * hash + Objects.hashCode(this.mailcoach);
        hash = 59 * hash + Objects.hashCode(this.nomcoach);
        hash = 59 * hash + Objects.hashCode(this.prenomcoach);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coach other = (Coach) obj;
        if (!Objects.equals(this.mailadmin, other.mailadmin)) {
            return false;
        }
        if (!Objects.equals(this.mailcoach, other.mailcoach)) {
            return false;
        }
        if (!Objects.equals(this.nomcoach, other.nomcoach)) {
            return false;
        }
        if (!Objects.equals(this.prenomcoach, other.prenomcoach)) {
            return false;
        }
        if (!Objects.equals(this.idcoach, other.idcoach)) {
            return false;
        }
        return true;
    }




}


