package DAO;
// Generated 18 fvr. 2019 11:30:37 by Hibernate Tools 4.3.1



/**
 * ContenirexId generated by hbm2java
 */
public class ContenirexId  implements java.io.Serializable {


     private int idscprog;
     private int idtypeex;

    public ContenirexId() {
    }

    public ContenirexId(int idscprog, int idtypeex) {
       this.idscprog = idscprog;
       this.idtypeex = idtypeex;
    }
   
    public int getIdscprog() {
        return this.idscprog;
    }
    
    public void setIdscprog(int idscprog) {
        this.idscprog = idscprog;
    }
    public int getIdtypeex() {
        return this.idtypeex;
    }
    
    public void setIdtypeex(int idtypeex) {
        this.idtypeex = idtypeex;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContenirexId) ) return false;
		 ContenirexId castOther = ( ContenirexId ) other; 
         
		 return (this.getIdscprog()==castOther.getIdscprog())
 && (this.getIdtypeex()==castOther.getIdtypeex());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdscprog();
         result = 37 * result + this.getIdtypeex();
         return result;
   }   


}


