package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Contenirex generated by hbm2java
 */
public class Contenirex  implements java.io.Serializable {


     private ContenirexId id;
     private Seanceprogamme seanceprogamme;
     private Typeexercice typeexercice;
     private Integer ordreex;
     private Float temps;
     private Integer nbrep;

    public Contenirex() {
    }

	
    public Contenirex(ContenirexId id, Seanceprogamme seanceprogamme, Typeexercice typeexercice) {
        this.id = id;
        this.seanceprogamme = seanceprogamme;
        this.typeexercice = typeexercice;
    }
    public Contenirex(ContenirexId id, Seanceprogamme seanceprogamme, Typeexercice typeexercice, Integer ordreex, Float temps, Integer nbrep) {
       this.id = id;
       this.seanceprogamme = seanceprogamme;
       this.typeexercice = typeexercice;
       this.ordreex = ordreex;
       this.temps = temps;
       this.nbrep = nbrep;
    }
   
    public ContenirexId getId() {
        return this.id;
    }
    
    public void setId(ContenirexId id) {
        this.id = id;
    }
    public Seanceprogamme getSeanceprogamme() {
        return this.seanceprogamme;
    }
    
    public void setSeanceprogamme(Seanceprogamme seanceprogamme) {
        this.seanceprogamme = seanceprogamme;
    }
    public Typeexercice getTypeexercice() {
        return this.typeexercice;
    }
    
    public void setTypeexercice(Typeexercice typeexercice) {
        this.typeexercice = typeexercice;
    }
    public Integer getOrdreex() {
        return this.ordreex;
    }
    
    public void setOrdreex(Integer ordreex) {
        this.ordreex = ordreex;
    }
    public Float getTemps() {
        return this.temps;
    }
    
    public void setTemps(Float temps) {
        this.temps = temps;
    }
    public Integer getNbrep() {
        return this.nbrep;
    }
    
    public void setNbrep(Integer nbrep) {
        this.nbrep = nbrep;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 61 * hash + Objects.hashCode(this.id);
        hash = 61 * hash + Objects.hashCode(this.ordreex);
        hash = 61 * hash + Objects.hashCode(this.temps);
        hash = 61 * hash + Objects.hashCode(this.nbrep);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Contenirex other = (Contenirex) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.ordreex, other.ordreex)) {
            return false;
        }
        if (!Objects.equals(this.temps, other.temps)) {
            return false;
        }
        if (!Objects.equals(this.nbrep, other.nbrep)) {
            return false;
        }
        return true;
    }




}


