package DAO;
// Generated 18 fvr. 2019 11:30:37 by Hibernate Tools 4.3.1



/**
 * EvaluerexcerciceId generated by hbm2java
 */
public class EvaluerexcerciceId  implements java.io.Serializable {


     private int idev;
     private int idtypeex;
     private int idsb;
     private int idcli;

    public EvaluerexcerciceId() {
    }

    public EvaluerexcerciceId(int idev, int idtypeex, int idsb, int idcli) {
       this.idev = idev;
       this.idtypeex = idtypeex;
       this.idsb = idsb;
       this.idcli = idcli;
    }
   
    public int getIdev() {
        return this.idev;
    }
    
    public void setIdev(int idev) {
        this.idev = idev;
    }
    public int getIdtypeex() {
        return this.idtypeex;
    }
    
    public void setIdtypeex(int idtypeex) {
        this.idtypeex = idtypeex;
    }
    public int getIdsb() {
        return this.idsb;
    }
    
    public void setIdsb(int idsb) {
        this.idsb = idsb;
    }
    public int getIdcli() {
        return this.idcli;
    }
    
    public void setIdcli(int idcli) {
        this.idcli = idcli;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluerexcerciceId) ) return false;
		 EvaluerexcerciceId castOther = ( EvaluerexcerciceId ) other; 
         
		 return (this.getIdev()==castOther.getIdev())
 && (this.getIdtypeex()==castOther.getIdtypeex())
 && (this.getIdsb()==castOther.getIdsb())
 && (this.getIdcli()==castOther.getIdcli());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdev();
         result = 37 * result + this.getIdtypeex();
         result = 37 * result + this.getIdsb();
         result = 37 * result + this.getIdcli();
         return result;
   }   


}


