package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Niveau generated by hbm2java
 */
public class Niveau  implements java.io.Serializable {


     private String libniv;
     private Set typeexercices = new HashSet(0);

    public Niveau() {
    }

	
    public Niveau(String libniv) {
        this.libniv = libniv;
    }
    public Niveau(String libniv, Set typeexercices) {
       this.libniv = libniv;
       this.typeexercices = typeexercices;
    }
   
    public String getLibniv() {
        return this.libniv;
    }
    
    public void setLibniv(String libniv) {
        this.libniv = libniv;
    }
    public Set getTypeexercices() {
        return this.typeexercices;
    }
    
    public void setTypeexercices(Set typeexercices) {
        this.typeexercices = typeexercices;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + Objects.hashCode(this.libniv);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Niveau other = (Niveau) obj;
        if (!Objects.equals(this.libniv, other.libniv)) {
            return false;
        }
        return true;
    }




}


