package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme  implements java.io.Serializable {


     private Integer idprog;
     private Typeprogramme typeprogramme;
     private String libprog;
     private String desprog;
     private Set avoirResultats = new HashSet(0);
     private Set clients = new HashSet(0);
     private Set affecterscs = new HashSet(0);

    public Programme() {
    }

	
    public Programme(Typeprogramme typeprogramme) {
        this.typeprogramme = typeprogramme;
    }
    public Programme(Typeprogramme typeprogramme, String libprog, String desprog, Set avoirResultats, Set clients, Set affecterscs) {
       this.typeprogramme = typeprogramme;
       this.libprog = libprog;
       this.desprog = desprog;
       this.avoirResultats = avoirResultats;
       this.clients = clients;
       this.affecterscs = affecterscs;
    }
   
    public Integer getIdprog() {
        return this.idprog;
    }
    
    public void setIdprog(Integer idprog) {
        this.idprog = idprog;
    }
    public Typeprogramme getTypeprogramme() {
        return this.typeprogramme;
    }
    
    public void setTypeprogramme(Typeprogramme typeprogramme) {
        this.typeprogramme = typeprogramme;
    }
    public String getLibprog() {
        return this.libprog;
    }
    
    public void setLibprog(String libprog) {
        this.libprog = libprog;
    }
    public String getDesprog() {
        return this.desprog;
    }
    
    public void setDesprog(String desprog) {
        this.desprog = desprog;
    }
    public Set getAvoirResultats() {
        return this.avoirResultats;
    }
    
    public void setAvoirResultats(Set avoirResultats) {
        this.avoirResultats = avoirResultats;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
    public Set getAffecterscs() {
        return this.affecterscs;
    }
    
    public void setAffecterscs(Set affecterscs) {
        this.affecterscs = affecterscs;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.idprog);
        hash = 79 * hash + Objects.hashCode(this.libprog);
        hash = 79 * hash + Objects.hashCode(this.desprog);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Programme other = (Programme) obj;
        if (!Objects.equals(this.libprog, other.libprog)) {
            return false;
        }
        if (!Objects.equals(this.desprog, other.desprog)) {
            return false;
        }
        if (!Objects.equals(this.idprog, other.idprog)) {
            return false;
        }
        return true;
    }




}


