package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Seanceprogamme generated by hbm2java
 */
public class Seanceprogamme  implements java.io.Serializable {


     private Integer idscprog;
     private Seance seance;
     private Typeseance typeseance;
     private Float dureesc;
     private String echauffsc;
     private String dessc;
     private Set avoirResultats = new HashSet(0);
     private Set contenirexes = new HashSet(0);

    public Seanceprogamme() {
    }

	
    public Seanceprogamme(Seance seance, Typeseance typeseance) {
        this.seance = seance;
        this.typeseance = typeseance;
    }
    public Seanceprogamme(Seance seance, Typeseance typeseance, Float dureesc, String echauffsc, String dessc, Set avoirResultats, Set contenirexes) {
       this.seance = seance;
       this.typeseance = typeseance;
       this.dureesc = dureesc;
       this.echauffsc = echauffsc;
       this.dessc = dessc;
       this.avoirResultats = avoirResultats;
       this.contenirexes = contenirexes;
    }
   
    public Integer getIdscprog() {
        return this.idscprog;
    }
    
    public void setIdscprog(Integer idscprog) {
        this.idscprog = idscprog;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public Typeseance getTypeseance() {
        return this.typeseance;
    }
    
    public void setTypeseance(Typeseance typeseance) {
        this.typeseance = typeseance;
    }
    public Float getDureesc() {
        return this.dureesc;
    }
    
    public void setDureesc(Float dureesc) {
        this.dureesc = dureesc;
    }
    public String getEchauffsc() {
        return this.echauffsc;
    }
    
    public void setEchauffsc(String echauffsc) {
        this.echauffsc = echauffsc;
    }
    public String getDessc() {
        return this.dessc;
    }
    
    public void setDessc(String dessc) {
        this.dessc = dessc;
    }
    public Set getAvoirResultats() {
        return this.avoirResultats;
    }
    
    public void setAvoirResultats(Set avoirResultats) {
        this.avoirResultats = avoirResultats;
    }
    public Set getContenirexes() {
        return this.contenirexes;
    }
    
    public void setContenirexes(Set contenirexes) {
        this.contenirexes = contenirexes;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + Objects.hashCode(this.idscprog);
        hash = 17 * hash + Objects.hashCode(this.dureesc);
        hash = 17 * hash + Objects.hashCode(this.echauffsc);
        hash = 17 * hash + Objects.hashCode(this.dessc);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seanceprogamme other = (Seanceprogamme) obj;
        if (!Objects.equals(this.echauffsc, other.echauffsc)) {
            return false;
        }
        if (!Objects.equals(this.dessc, other.dessc)) {
            return false;
        }
        if (!Objects.equals(this.idscprog, other.idscprog)) {
            return false;
        }
        if (!Objects.equals(this.dureesc, other.dureesc)) {
            return false;
        }
        return true;
    }




}


