package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Seancebilan generated by hbm2java
 */
public class Seancebilan  implements java.io.Serializable {


     private Integer idsb;
     private Client client;
     private Seance seance;
     private String etatsb;
     private Float poidssb;
     private Float fcsb;
     private Float fcciblesb;
     private Float fcallongesbev1;
     private Float fcallongesbev2;
     private Float fcflexsbev1;
     private Float fcflexsbev2;
     private Float fcexallongesbev1;
     private Float fcexallongesbev2;
     private Float mbras;
     private Float mpoitrine;
     private Float mtaille;
     private Float mhanches;
     private Float mcuisses;
     private Set evaluerexcercices = new HashSet(0);

    public Seancebilan() {
    }

	
    public Seancebilan(Seance seance) {
        this.seance = seance;
    }
    public Seancebilan(Client client, Seance seance, String etatsb, Float poidssb, Float fcsb, Float fcciblesb, Float fcallongesbev1, Float fcallongesbev2, Float fcflexsbev1, Float fcflexsbev2, Float fcexallongesbev1, Float fcexallongesbev2, Float mbras, Float mpoitrine, Float mtaille, Float mhanches, Float mcuisses, Set evaluerexcercices) {
       this.client = client;
       this.seance = seance;
       this.etatsb = etatsb;
       this.poidssb = poidssb;
       this.fcsb = fcsb;
       this.fcciblesb = fcciblesb;
       this.fcallongesbev1 = fcallongesbev1;
       this.fcallongesbev2 = fcallongesbev2;
       this.fcflexsbev1 = fcflexsbev1;
       this.fcflexsbev2 = fcflexsbev2;
       this.fcexallongesbev1 = fcexallongesbev1;
       this.fcexallongesbev2 = fcexallongesbev2;
       this.mbras = mbras;
       this.mpoitrine = mpoitrine;
       this.mtaille = mtaille;
       this.mhanches = mhanches;
       this.mcuisses = mcuisses;
       this.evaluerexcercices = evaluerexcercices;
    }
   
    public Integer getIdsb() {
        return this.idsb;
    }
    
    public void setIdsb(Integer idsb) {
        this.idsb = idsb;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Seance getSeance() {
        return this.seance;
    }
    
    public void setSeance(Seance seance) {
        this.seance = seance;
    }
    public String getEtatsb() {
        return this.etatsb;
    }
    
    public void setEtatsb(String etatsb) {
        this.etatsb = etatsb;
    }
    public Float getPoidssb() {
        return this.poidssb;
    }
    
    public void setPoidssb(Float poidssb) {
        this.poidssb = poidssb;
    }
    public Float getFcsb() {
        return this.fcsb;
    }
    
    public void setFcsb(Float fcsb) {
        this.fcsb = fcsb;
    }
    public Float getFcciblesb() {
        return this.fcciblesb;
    }
    
    public void setFcciblesb(Float fcciblesb) {
        this.fcciblesb = fcciblesb;
    }
    public Float getFcallongesbev1() {
        return this.fcallongesbev1;
    }
    
    public void setFcallongesbev1(Float fcallongesbev1) {
        this.fcallongesbev1 = fcallongesbev1;
    }
    public Float getFcallongesbev2() {
        return this.fcallongesbev2;
    }
    
    public void setFcallongesbev2(Float fcallongesbev2) {
        this.fcallongesbev2 = fcallongesbev2;
    }
    public Float getFcflexsbev1() {
        return this.fcflexsbev1;
    }
    
    public void setFcflexsbev1(Float fcflexsbev1) {
        this.fcflexsbev1 = fcflexsbev1;
    }
    public Float getFcflexsbev2() {
        return this.fcflexsbev2;
    }
    
    public void setFcflexsbev2(Float fcflexsbev2) {
        this.fcflexsbev2 = fcflexsbev2;
    }
    public Float getFcexallongesbev1() {
        return this.fcexallongesbev1;
    }
    
    public void setFcexallongesbev1(Float fcexallongesbev1) {
        this.fcexallongesbev1 = fcexallongesbev1;
    }
    public Float getFcexallongesbev2() {
        return this.fcexallongesbev2;
    }
    
    public void setFcexallongesbev2(Float fcexallongesbev2) {
        this.fcexallongesbev2 = fcexallongesbev2;
    }
    public Float getMbras() {
        return this.mbras;
    }
    
    public void setMbras(Float mbras) {
        this.mbras = mbras;
    }
    public Float getMpoitrine() {
        return this.mpoitrine;
    }
    
    public void setMpoitrine(Float mpoitrine) {
        this.mpoitrine = mpoitrine;
    }
    public Float getMtaille() {
        return this.mtaille;
    }
    
    public void setMtaille(Float mtaille) {
        this.mtaille = mtaille;
    }
    public Float getMhanches() {
        return this.mhanches;
    }
    
    public void setMhanches(Float mhanches) {
        this.mhanches = mhanches;
    }
    public Float getMcuisses() {
        return this.mcuisses;
    }
    
    public void setMcuisses(Float mcuisses) {
        this.mcuisses = mcuisses;
    }
    public Set getEvaluerexcercices() {
        return this.evaluerexcercices;
    }
    
    public void setEvaluerexcercices(Set evaluerexcercices) {
        this.evaluerexcercices = evaluerexcercices;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.idsb);
        hash = 17 * hash + Objects.hashCode(this.etatsb);
        hash = 17 * hash + Objects.hashCode(this.poidssb);
        hash = 17 * hash + Objects.hashCode(this.fcsb);
        hash = 17 * hash + Objects.hashCode(this.fcciblesb);
        hash = 17 * hash + Objects.hashCode(this.fcallongesbev1);
        hash = 17 * hash + Objects.hashCode(this.fcallongesbev2);
        hash = 17 * hash + Objects.hashCode(this.fcflexsbev1);
        hash = 17 * hash + Objects.hashCode(this.fcflexsbev2);
        hash = 17 * hash + Objects.hashCode(this.fcexallongesbev1);
        hash = 17 * hash + Objects.hashCode(this.fcexallongesbev2);
        hash = 17 * hash + Objects.hashCode(this.mbras);
        hash = 17 * hash + Objects.hashCode(this.mpoitrine);
        hash = 17 * hash + Objects.hashCode(this.mtaille);
        hash = 17 * hash + Objects.hashCode(this.mhanches);
        hash = 17 * hash + Objects.hashCode(this.mcuisses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Seancebilan other = (Seancebilan) obj;
        if (!Objects.equals(this.etatsb, other.etatsb)) {
            return false;
        }
        if (!Objects.equals(this.idsb, other.idsb)) {
            return false;
        }
        if (!Objects.equals(this.poidssb, other.poidssb)) {
            return false;
        }
        if (!Objects.equals(this.fcsb, other.fcsb)) {
            return false;
        }
        if (!Objects.equals(this.fcciblesb, other.fcciblesb)) {
            return false;
        }
        if (!Objects.equals(this.fcallongesbev1, other.fcallongesbev1)) {
            return false;
        }
        if (!Objects.equals(this.fcallongesbev2, other.fcallongesbev2)) {
            return false;
        }
        if (!Objects.equals(this.fcflexsbev1, other.fcflexsbev1)) {
            return false;
        }
        if (!Objects.equals(this.fcflexsbev2, other.fcflexsbev2)) {
            return false;
        }
        if (!Objects.equals(this.fcexallongesbev1, other.fcexallongesbev1)) {
            return false;
        }
        if (!Objects.equals(this.fcexallongesbev2, other.fcexallongesbev2)) {
            return false;
        }
        if (!Objects.equals(this.mbras, other.mbras)) {
            return false;
        }
        if (!Objects.equals(this.mpoitrine, other.mpoitrine)) {
            return false;
        }
        if (!Objects.equals(this.mtaille, other.mtaille)) {
            return false;
        }
        if (!Objects.equals(this.mhanches, other.mhanches)) {
            return false;
        }
        if (!Objects.equals(this.mcuisses, other.mcuisses)) {
            return false;
        }
        return true;
    }




}


