package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Statutclient generated by hbm2java
 */
public class Statutclient  implements java.io.Serializable {


     private String libstatut;
     private Set clients = new HashSet(0);

    public Statutclient() {
    }

	
    public Statutclient(String libstatut) {
        this.libstatut = libstatut;
    }
    public Statutclient(String libstatut, Set clients) {
       this.libstatut = libstatut;
       this.clients = clients;
    }
   
    public String getLibstatut() {
        return this.libstatut;
    }
    
    public void setLibstatut(String libstatut) {
        this.libstatut = libstatut;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.libstatut);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Statutclient other = (Statutclient) obj;
        if (!Objects.equals(this.libstatut, other.libstatut)) {
            return false;
        }
        return true;
    }




}


