package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Typeabonnement generated by hbm2java
 */
public class Typeabonnement  implements java.io.Serializable {


     private String libabon;
     private Set clients = new HashSet(0);

    public Typeabonnement() {
    }

	
    public Typeabonnement(String libabon) {
        this.libabon = libabon;
    }
    public Typeabonnement(String libabon, Set clients) {
       this.libabon = libabon;
       this.clients = clients;
    }
   
    public String getLibabon() {
        return this.libabon;
    }
    
    public void setLibabon(String libabon) {
        this.libabon = libabon;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + Objects.hashCode(this.libabon);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Typeabonnement other = (Typeabonnement) obj;
        if (!Objects.equals(this.libabon, other.libabon)) {
            return false;
        }
        return true;
    }




}


