package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Typeprogramme generated by hbm2java
 */
public class Typeprogramme  implements java.io.Serializable {


     private Integer idtp;
     private String libtp;
     private Set programmes = new HashSet(0);

    public Typeprogramme() {
    }

    public Typeprogramme(String libtp, Set programmes) {
       this.libtp = libtp;
       this.programmes = programmes;
    }
   
    public Integer getIdtp() {
        return this.idtp;
    }
    
    public void setIdtp(Integer idtp) {
        this.idtp = idtp;
    }
    public String getLibtp() {
        return this.libtp;
    }
    
    public void setLibtp(String libtp) {
        this.libtp = libtp;
    }
    public Set getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Set programmes) {
        this.programmes = programmes;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.idtp);
        hash = 97 * hash + Objects.hashCode(this.libtp);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Typeprogramme other = (Typeprogramme) obj;
        if (!Objects.equals(this.libtp, other.libtp)) {
            return false;
        }
        if (!Objects.equals(this.idtp, other.idtp)) {
            return false;
        }
        return true;
    }




}


