package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Typeseance generated by hbm2java
 */
public class Typeseance  implements java.io.Serializable {


     private Integer idts;
     private String libts;
     private Set seanceprogammes = new HashSet(0);

    public Typeseance() {
    }

    public Typeseance(String libts, Set seanceprogammes) {
       this.libts = libts;
       this.seanceprogammes = seanceprogammes;
    }
   
    public Integer getIdts() {
        return this.idts;
    }
    
    public void setIdts(Integer idts) {
        this.idts = idts;
    }
    public String getLibts() {
        return this.libts;
    }
    
    public void setLibts(String libts) {
        this.libts = libts;
    }
    public Set getSeanceprogammes() {
        return this.seanceprogammes;
    }
    
    public void setSeanceprogammes(Set seanceprogammes) {
        this.seanceprogammes = seanceprogammes;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + Objects.hashCode(this.idts);
        hash = 67 * hash + Objects.hashCode(this.libts);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Typeseance other = (Typeseance) obj;
        if (!Objects.equals(this.libts, other.libts)) {
            return false;
        }
        if (!Objects.equals(this.idts, other.idts)) {
            return false;
        }
        return true;
    }




}


