package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Typeexercice generated by hbm2java
 */
public class Typeexercice  implements java.io.Serializable {


     private Integer idtypeex;
     private String libtypeex;
     private String imgtypeex;
     private String objtypeex;
     private String destypeex;
     private Set avoirResultats = new HashSet(0);
     private Set evaluerexcercices = new HashSet(0);
     private Set niveaus = new HashSet(0);
     private Set contenirexes = new HashSet(0);

    public Typeexercice() {
    }

    public Typeexercice(String libtypeex, String imgtypeex, String objtypeex, String destypeex, Set avoirResultats, Set evaluerexcercices, Set niveaus, Set contenirexes) {
       this.libtypeex = libtypeex;
       this.imgtypeex = imgtypeex;
       this.objtypeex = objtypeex;
       this.destypeex = destypeex;
       this.avoirResultats = avoirResultats;
       this.evaluerexcercices = evaluerexcercices;
       this.niveaus = niveaus;
       this.contenirexes = contenirexes;
    }
   
    public Integer getIdtypeex() {
        return this.idtypeex;
    }
    
    public void setIdtypeex(Integer idtypeex) {
        this.idtypeex = idtypeex;
    }
    public String getLibtypeex() {
        return this.libtypeex;
    }
    
    public void setLibtypeex(String libtypeex) {
        this.libtypeex = libtypeex;
    }
    public String getImgtypeex() {
        return this.imgtypeex;
    }
    
    public void setImgtypeex(String imgtypeex) {
        this.imgtypeex = imgtypeex;
    }
    public String getObjtypeex() {
        return this.objtypeex;
    }
    
    public void setObjtypeex(String objtypeex) {
        this.objtypeex = objtypeex;
    }
    public String getDestypeex() {
        return this.destypeex;
    }
    
    public void setDestypeex(String destypeex) {
        this.destypeex = destypeex;
    }
    public Set getAvoirResultats() {
        return this.avoirResultats;
    }
    
    public void setAvoirResultats(Set avoirResultats) {
        this.avoirResultats = avoirResultats;
    }
    public Set getEvaluerexcercices() {
        return this.evaluerexcercices;
    }
    
    public void setEvaluerexcercices(Set evaluerexcercices) {
        this.evaluerexcercices = evaluerexcercices;
    }
    public Set getNiveaus() {
        return this.niveaus;
    }
    
    public void setNiveaus(Set niveaus) {
        this.niveaus = niveaus;
    }
    public Set getContenirexes() {
        return this.contenirexes;
    }
    
    public void setContenirexes(Set contenirexes) {
        this.contenirexes = contenirexes;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + Objects.hashCode(this.idtypeex);
        hash = 59 * hash + Objects.hashCode(this.libtypeex);
        hash = 59 * hash + Objects.hashCode(this.imgtypeex);
        hash = 59 * hash + Objects.hashCode(this.objtypeex);
        hash = 59 * hash + Objects.hashCode(this.destypeex);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Typeexercice other = (Typeexercice) obj;
        if (!Objects.equals(this.libtypeex, other.libtypeex)) {
            return false;
        }
        if (!Objects.equals(this.imgtypeex, other.imgtypeex)) {
            return false;
        }
        if (!Objects.equals(this.objtypeex, other.objtypeex)) {
            return false;
        }
        if (!Objects.equals(this.destypeex, other.destypeex)) {
            return false;
        }
        if (!Objects.equals(this.idtypeex, other.idtypeex)) {
            return false;
        }
        return true;
    }




}


