package DAO;
// Generated 18 f�vr. 2019 11:30:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Typeclient generated by hbm2java
 */
public class Typeclient  implements java.io.Serializable {


     private Integer idtc;
     private String libtc;
     private Set clients = new HashSet(0);

    public Typeclient() {
    }

    public Typeclient(String libtc, Set clients) {
       this.libtc = libtc;
       this.clients = clients;
    }
   
    public Integer getIdtc() {
        return this.idtc;
    }
    
    public void setIdtc(Integer idtc) {
        this.idtc = idtc;
    }
    public String getLibtc() {
        return this.libtc;
    }
    
    public void setLibtc(String libtc) {
        this.libtc = libtc;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.idtc);
        hash = 89 * hash + Objects.hashCode(this.libtc);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Typeclient other = (Typeclient) obj;
        if (!Objects.equals(this.libtc, other.libtc)) {
            return false;
        }
        if (!Objects.equals(this.idtc, other.idtc)) {
            return false;
        }
        return true;
    }




}


